# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/users/mercolino/PycharmProjects/Config_Replicator/ui/mainwindow.ui'
#
# Created: Wed May 14 19:09:53 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(740, 569)
        MainWindow.setFocusPolicy(QtCore.Qt.TabFocus)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 3, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.threadsHorizontalSlider = QtGui.QSlider(self.centralwidget)
        self.threadsHorizontalSlider.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.threadsHorizontalSlider.setAutoFillBackground(False)
        self.threadsHorizontalSlider.setInputMethodHints(QtCore.Qt.ImhNone)
        self.threadsHorizontalSlider.setMinimum(1)
        self.threadsHorizontalSlider.setMaximum(500)
        self.threadsHorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.threadsHorizontalSlider.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.threadsHorizontalSlider.setTickInterval(50)
        self.threadsHorizontalSlider.setObjectName(_fromUtf8("threadsHorizontalSlider"))
        self.gridLayout_2.addWidget(self.threadsHorizontalSlider, 0, 1, 1, 1)
        self.threadsLabel = QtGui.QLabel(self.centralwidget)
        self.threadsLabel.setObjectName(_fromUtf8("threadsLabel"))
        self.gridLayout_2.addWidget(self.threadsLabel, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 3, 1, 1)
        self.threadSpinBox = QtGui.QSpinBox(self.centralwidget)
        self.threadSpinBox.setMinimumSize(QtCore.QSize(60, 40))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.threadSpinBox.setFont(font)
        self.threadSpinBox.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.threadSpinBox.setWrapping(False)
        self.threadSpinBox.setFrame(True)
        self.threadSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.threadSpinBox.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.threadSpinBox.setAccelerated(False)
        self.threadSpinBox.setSuffix(_fromUtf8(""))
        self.threadSpinBox.setPrefix(_fromUtf8(""))
        self.threadSpinBox.setMaximum(500)
        self.threadSpinBox.setProperty("value", 1)
        self.threadSpinBox.setObjectName(_fromUtf8("threadSpinBox"))
        self.gridLayout_2.addWidget(self.threadSpinBox, 0, 2, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 1, 0, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.listLabel = QtGui.QLabel(self.centralwidget)
        self.listLabel.setFrameShape(QtGui.QFrame.NoFrame)
        self.listLabel.setObjectName(_fromUtf8("listLabel"))
        self.horizontalLayout_2.addWidget(self.listLabel)
        self.listPushButton = QtGui.QPushButton(self.centralwidget)
        self.listPushButton.setObjectName(_fromUtf8("listPushButton"))
        self.horizontalLayout_2.addWidget(self.listPushButton)
        self.listNameLabel = QtGui.QLabel(self.centralwidget)
        self.listNameLabel.setObjectName(_fromUtf8("listNameLabel"))
        self.horizontalLayout_2.addWidget(self.listNameLabel)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.saveListPushButton = QtGui.QPushButton(self.centralwidget)
        self.saveListPushButton.setObjectName(_fromUtf8("saveListPushButton"))
        self.horizontalLayout_2.addWidget(self.saveListPushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.listTextEdit = QtGui.QTextEdit(self.centralwidget)
        self.listTextEdit.setEnabled(False)
        self.listTextEdit.setObjectName(_fromUtf8("listTextEdit"))
        self.verticalLayout_2.addWidget(self.listTextEdit)
        self.gridLayout.addLayout(self.verticalLayout_2, 4, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.scriptLabel = QtGui.QLabel(self.centralwidget)
        self.scriptLabel.setObjectName(_fromUtf8("scriptLabel"))
        self.horizontalLayout.addWidget(self.scriptLabel)
        self.scriptPushButton = QtGui.QPushButton(self.centralwidget)
        self.scriptPushButton.setObjectName(_fromUtf8("scriptPushButton"))
        self.horizontalLayout.addWidget(self.scriptPushButton)
        self.scriptNameLabel = QtGui.QLabel(self.centralwidget)
        self.scriptNameLabel.setObjectName(_fromUtf8("scriptNameLabel"))
        self.horizontalLayout.addWidget(self.scriptNameLabel)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.saveScriptPushButton = QtGui.QPushButton(self.centralwidget)
        self.saveScriptPushButton.setObjectName(_fromUtf8("saveScriptPushButton"))
        self.horizontalLayout.addWidget(self.saveScriptPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.scriptTextEdit = QtGui.QTextEdit(self.centralwidget)
        self.scriptTextEdit.setEnabled(False)
        self.scriptTextEdit.setObjectName(_fromUtf8("scriptTextEdit"))
        self.verticalLayout.addWidget(self.scriptTextEdit)
        self.gridLayout.addLayout(self.verticalLayout, 2, 0, 1, 1)
        self.alertLabel = QtGui.QLabel(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.alertLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.alertLabel.setFont(font)
        self.alertLabel.setObjectName(_fromUtf8("alertLabel"))
        self.gridLayout.addWidget(self.alertLabel, 5, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setFocusPolicy(QtCore.Qt.TabFocus)
        self.toolBar.setMovable(False)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionExit = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("ui/exit.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionExit.setIcon(icon)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionConnect = QtGui.QAction(MainWindow)
        self.actionConnect.setEnabled(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("ui/connect_disabled.png")), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("ui/connect_normal.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("ui/connect_disabled.png")), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.actionConnect.setIcon(icon1)
        self.actionConnect.setObjectName(_fromUtf8("actionConnect"))
        self.actionClear = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("ui/edit_clear.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClear.setIcon(icon2)
        self.actionClear.setObjectName(_fromUtf8("actionClear"))
        self.actionReports = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("ui/reports.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReports.setIcon(icon3)
        self.actionReports.setObjectName(_fromUtf8("actionReports"))
        self.actionSettings = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("ui/settings.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSettings.setIcon(icon4)
        self.actionSettings.setObjectName(_fromUtf8("actionSettings"))
        self.actionHelp = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("ui/help.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelp.setIcon(icon5)
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.toolBar.addAction(self.actionConnect)
        self.toolBar.addAction(self.actionReports)
        self.toolBar.addAction(self.actionClear)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSettings)
        self.toolBar.addAction(self.actionHelp)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionExit)
        self.threadsLabel.setBuddy(self.threadsHorizontalSlider)
        self.listLabel.setBuddy(self.listPushButton)
        self.scriptLabel.setBuddy(self.scriptPushButton)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QObject.connect(self.threadsHorizontalSlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.threadSpinBox.setValue)
        QtCore.QObject.connect(self.threadSpinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.threadsHorizontalSlider.setValue)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.threadSpinBox, self.scriptPushButton)
        MainWindow.setTabOrder(self.scriptPushButton, self.saveScriptPushButton)
        MainWindow.setTabOrder(self.saveScriptPushButton, self.scriptTextEdit)
        MainWindow.setTabOrder(self.scriptTextEdit, self.listPushButton)
        MainWindow.setTabOrder(self.listPushButton, self.saveListPushButton)
        MainWindow.setTabOrder(self.saveListPushButton, self.listTextEdit)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Config Replicator", None))
        self.threadsLabel.setText(_translate("MainWindow", "Number of &Threads to spawn:", None))
        self.listLabel.setText(_translate("MainWindow", "Select a Destination &List File:", None))
        self.listPushButton.setText(_translate("MainWindow", "Load Dest List ...", None))
        self.listNameLabel.setText(_translate("MainWindow", "Not Selected", None))
        self.saveListPushButton.setText(_translate("MainWindow", "Save Dest List", None))
        self.scriptLabel.setText(_translate("MainWindow", "Select a &Script File:", None))
        self.scriptPushButton.setText(_translate("MainWindow", "Load Script ...", None))
        self.scriptNameLabel.setText(_translate("MainWindow", "Not Selected", None))
        self.saveScriptPushButton.setText(_translate("MainWindow", "Save Script", None))
        self.alertLabel.setText(_translate("MainWindow", "Alerts", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionExit.setToolTip(_translate("MainWindow", "Exit", None))
        self.actionConnect.setText(_translate("MainWindow", "Connect", None))
        self.actionConnect.setToolTip(_translate("MainWindow", "Connect", None))
        self.actionClear.setText(_translate("MainWindow", "Clear", None))
        self.actionClear.setToolTip(_translate("MainWindow", "Clear", None))
        self.actionReports.setText(_translate("MainWindow", "Reports", None))
        self.actionReports.setToolTip(_translate("MainWindow", "Resports", None))
        self.actionSettings.setText(_translate("MainWindow", "Settings", None))
        self.actionSettings.setToolTip(_translate("MainWindow", "Settings", None))
        self.actionHelp.setText(_translate("MainWindow", "Help", None))
        self.actionHelp.setToolTip(_translate("MainWindow", "Help", None))

