# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(740, 569)
        MainWindow.setFocusPolicy(QtCore.Qt.TabFocus)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 3, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.threadsHorizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.threadsHorizontalSlider.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.threadsHorizontalSlider.setAutoFillBackground(False)
        self.threadsHorizontalSlider.setInputMethodHints(QtCore.Qt.ImhNone)
        self.threadsHorizontalSlider.setMinimum(1)
        self.threadsHorizontalSlider.setMaximum(500)
        self.threadsHorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.threadsHorizontalSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.threadsHorizontalSlider.setTickInterval(50)
        self.threadsHorizontalSlider.setObjectName("threadsHorizontalSlider")
        self.gridLayout_2.addWidget(self.threadsHorizontalSlider, 0, 1, 1, 1)
        self.threadsLabel = QtWidgets.QLabel(self.centralwidget)
        self.threadsLabel.setObjectName("threadsLabel")
        self.gridLayout_2.addWidget(self.threadsLabel, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 3, 1, 1)
        self.threadSpinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.threadSpinBox.setMinimumSize(QtCore.QSize(60, 40))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.threadSpinBox.setFont(font)
        self.threadSpinBox.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.threadSpinBox.setWrapping(False)
        self.threadSpinBox.setFrame(True)
        self.threadSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.threadSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.threadSpinBox.setAccelerated(False)
        self.threadSpinBox.setSuffix("")
        self.threadSpinBox.setPrefix("")
        self.threadSpinBox.setMaximum(500)
        self.threadSpinBox.setProperty("value", 1)
        self.threadSpinBox.setObjectName("threadSpinBox")
        self.gridLayout_2.addWidget(self.threadSpinBox, 0, 2, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 1, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.listLabel = QtWidgets.QLabel(self.centralwidget)
        self.listLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listLabel.setObjectName("listLabel")
        self.horizontalLayout_2.addWidget(self.listLabel)
        self.listPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.listPushButton.setObjectName("listPushButton")
        self.horizontalLayout_2.addWidget(self.listPushButton)
        self.listNameLabel = QtWidgets.QLabel(self.centralwidget)
        self.listNameLabel.setObjectName("listNameLabel")
        self.horizontalLayout_2.addWidget(self.listNameLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.saveListPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveListPushButton.setObjectName("saveListPushButton")
        self.horizontalLayout_2.addWidget(self.saveListPushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.listTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.listTextEdit.setEnabled(False)
        self.listTextEdit.setObjectName("listTextEdit")
        self.verticalLayout_2.addWidget(self.listTextEdit)
        self.gridLayout.addLayout(self.verticalLayout_2, 4, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scriptLabel = QtWidgets.QLabel(self.centralwidget)
        self.scriptLabel.setObjectName("scriptLabel")
        self.horizontalLayout.addWidget(self.scriptLabel)
        self.scriptPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.scriptPushButton.setObjectName("scriptPushButton")
        self.horizontalLayout.addWidget(self.scriptPushButton)
        self.scriptNameLabel = QtWidgets.QLabel(self.centralwidget)
        self.scriptNameLabel.setObjectName("scriptNameLabel")
        self.horizontalLayout.addWidget(self.scriptNameLabel)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.saveScriptPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveScriptPushButton.setObjectName("saveScriptPushButton")
        self.horizontalLayout.addWidget(self.saveScriptPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.scriptTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.scriptTextEdit.setEnabled(False)
        self.scriptTextEdit.setObjectName("scriptTextEdit")
        self.verticalLayout.addWidget(self.scriptTextEdit)
        self.gridLayout.addLayout(self.verticalLayout, 2, 0, 1, 1)
        self.alertLabel = QtWidgets.QLabel(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.alertLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.alertLabel.setFont(font)
        self.alertLabel.setObjectName("alertLabel")
        self.gridLayout.addWidget(self.alertLabel, 5, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setFocusPolicy(QtCore.Qt.TabFocus)
        self.toolBar.setMovable(False)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionExit.setIcon(icon)
        self.actionExit.setObjectName("actionExit")
        self.actionConnect = QtWidgets.QAction(MainWindow)
        self.actionConnect.setEnabled(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("connect_normal.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon1.addPixmap(QtGui.QPixmap("connect_disabled.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap("connect_disabled.png"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        self.actionConnect.setIcon(icon1)
        self.actionConnect.setObjectName("actionConnect")
        self.actionClear = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("edit_clear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClear.setIcon(icon2)
        self.actionClear.setObjectName("actionClear")
        self.actionReports = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("reports.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReports.setIcon(icon3)
        self.actionReports.setObjectName("actionReports")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSettings.setIcon(icon4)
        self.actionSettings.setObjectName("actionSettings")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelp.setIcon(icon5)
        self.actionHelp.setObjectName("actionHelp")
        self.toolBar.addAction(self.actionConnect)
        self.toolBar.addAction(self.actionReports)
        self.toolBar.addAction(self.actionClear)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSettings)
        self.toolBar.addAction(self.actionHelp)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionExit)
        self.threadsLabel.setBuddy(self.threadsHorizontalSlider)
        self.listLabel.setBuddy(self.listPushButton)
        self.scriptLabel.setBuddy(self.scriptPushButton)

        self.retranslateUi(MainWindow)
        self.actionExit.triggered.connect(MainWindow.close)
        self.threadsHorizontalSlider.valueChanged['int'].connect(self.threadSpinBox.setValue)
        self.threadSpinBox.valueChanged['int'].connect(self.threadsHorizontalSlider.setValue)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.threadSpinBox, self.scriptPushButton)
        MainWindow.setTabOrder(self.scriptPushButton, self.saveScriptPushButton)
        MainWindow.setTabOrder(self.saveScriptPushButton, self.scriptTextEdit)
        MainWindow.setTabOrder(self.scriptTextEdit, self.listPushButton)
        MainWindow.setTabOrder(self.listPushButton, self.saveListPushButton)
        MainWindow.setTabOrder(self.saveListPushButton, self.listTextEdit)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Config Replicator"))
        self.threadsLabel.setText(_translate("MainWindow", "Number of &Threads to spawn:"))
        self.listLabel.setText(_translate("MainWindow", "Select a Destination &List File:"))
        self.listPushButton.setText(_translate("MainWindow", "Load Dest List ..."))
        self.listNameLabel.setText(_translate("MainWindow", "Not Selected"))
        self.saveListPushButton.setText(_translate("MainWindow", "Save Dest List"))
        self.scriptLabel.setText(_translate("MainWindow", "Select a &Script File:"))
        self.scriptPushButton.setText(_translate("MainWindow", "Load Script ..."))
        self.scriptNameLabel.setText(_translate("MainWindow", "Not Selected"))
        self.saveScriptPushButton.setText(_translate("MainWindow", "Save Script"))
        self.alertLabel.setText(_translate("MainWindow", "Alerts"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setToolTip(_translate("MainWindow", "Exit"))
        self.actionConnect.setText(_translate("MainWindow", "Connect"))
        self.actionConnect.setToolTip(_translate("MainWindow", "Connect"))
        self.actionClear.setText(_translate("MainWindow", "Clear"))
        self.actionClear.setToolTip(_translate("MainWindow", "Clear"))
        self.actionReports.setText(_translate("MainWindow", "Reports"))
        self.actionReports.setToolTip(_translate("MainWindow", "Resports"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionSettings.setToolTip(_translate("MainWindow", "Settings"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionHelp.setToolTip(_translate("MainWindow", "Help"))

