# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/users/mercolino/PycharmProjects/Config_Replicator/ui/monitoring.ui'
#
# Created: Fri May 16 14:27:57 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_monitoringDialog(object):
    def setupUi(self, monitoringDialog):
        monitoringDialog.setObjectName(_fromUtf8("monitoringDialog"))
        monitoringDialog.setWindowModality(QtCore.Qt.NonModal)
        monitoringDialog.resize(531, 295)
        monitoringDialog.setMinimumSize(QtCore.QSize(531, 295))
        monitoringDialog.setMaximumSize(QtCore.QSize(531, 295))
        monitoringDialog.setModal(True)
        self.line = QtGui.QFrame(monitoringDialog)
        self.line.setGeometry(QtCore.QRect(320, 20, 20, 81))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(monitoringDialog)
        self.line_2.setGeometry(QtCore.QRect(20, 110, 491, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.line_3 = QtGui.QFrame(monitoringDialog)
        self.line_3.setGeometry(QtCore.QRect(20, 150, 491, 20))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.widget = QtGui.QWidget(monitoringDialog)
        self.widget.setGeometry(QtCore.QRect(20, 20, 301, 81))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.monitoringScriptLabel = QtGui.QLabel(self.widget)
        self.monitoringScriptLabel.setObjectName(_fromUtf8("monitoringScriptLabel"))
        self.horizontalLayout.addWidget(self.monitoringScriptLabel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.monitoringListLabel = QtGui.QLabel(self.widget)
        self.monitoringListLabel.setObjectName(_fromUtf8("monitoringListLabel"))
        self.horizontalLayout_2.addWidget(self.monitoringListLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.monitoringThreadsLabel = QtGui.QLabel(self.widget)
        self.monitoringThreadsLabel.setFrameShape(QtGui.QFrame.NoFrame)
        self.monitoringThreadsLabel.setFrameShadow(QtGui.QFrame.Plain)
        self.monitoringThreadsLabel.setLineWidth(0)
        self.monitoringThreadsLabel.setObjectName(_fromUtf8("monitoringThreadsLabel"))
        self.horizontalLayout_3.addWidget(self.monitoringThreadsLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.widget1 = QtGui.QWidget(monitoringDialog)
        self.widget1.setGeometry(QtCore.QRect(350, 20, 158, 81))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_4 = QtGui.QLabel(self.widget1)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_2.addWidget(self.label_4)
        self.TotalLcdNumber = QtGui.QLCDNumber(self.widget1)
        self.TotalLcdNumber.setMinimumSize(QtCore.QSize(0, 50))
        self.TotalLcdNumber.setDigitCount(5)
        self.TotalLcdNumber.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.TotalLcdNumber.setObjectName(_fromUtf8("TotalLcdNumber"))
        self.verticalLayout_2.addWidget(self.TotalLcdNumber)
        self.widget2 = QtGui.QWidget(monitoringDialog)
        self.widget2.setGeometry(QtCore.QRect(20, 130, 491, 20))
        self.widget2.setObjectName(_fromUtf8("widget2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget2)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_5 = QtGui.QLabel(self.widget2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_4.addWidget(self.label_5)
        self.monitoringProgressBar = QtGui.QProgressBar(self.widget2)
        self.monitoringProgressBar.setMaximum(100)
        self.monitoringProgressBar.setProperty("value", 0)
        self.monitoringProgressBar.setTextVisible(False)
        self.monitoringProgressBar.setObjectName(_fromUtf8("monitoringProgressBar"))
        self.horizontalLayout_4.addWidget(self.monitoringProgressBar)
        self.monitoringProgressLabel = QtGui.QLabel(self.widget2)
        self.monitoringProgressLabel.setMinimumSize(QtCore.QSize(30, 0))
        self.monitoringProgressLabel.setObjectName(_fromUtf8("monitoringProgressLabel"))
        self.horizontalLayout_4.addWidget(self.monitoringProgressLabel)
        self.widget3 = QtGui.QWidget(monitoringDialog)
        self.widget3.setGeometry(QtCore.QRect(20, 170, 491, 81))
        self.widget3.setObjectName(_fromUtf8("widget3"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.widget3)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_6 = QtGui.QLabel(self.widget3)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_3.addWidget(self.label_6)
        self.SuccConnLcdNumber = QtGui.QLCDNumber(self.widget3)
        self.SuccConnLcdNumber.setMinimumSize(QtCore.QSize(0, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 178, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 178, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.SuccConnLcdNumber.setPalette(palette)
        self.SuccConnLcdNumber.setDigitCount(5)
        self.SuccConnLcdNumber.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.SuccConnLcdNumber.setObjectName(_fromUtf8("SuccConnLcdNumber"))
        self.verticalLayout_3.addWidget(self.SuccConnLcdNumber)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_8 = QtGui.QLabel(self.widget3)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_5.addWidget(self.label_8)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.elapsedTimeLcdNumber = QtGui.QLCDNumber(self.widget3)
        self.elapsedTimeLcdNumber.setMinimumSize(QtCore.QSize(0, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.elapsedTimeLcdNumber.setPalette(palette)
        self.elapsedTimeLcdNumber.setDigitCount(8)
        self.elapsedTimeLcdNumber.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.elapsedTimeLcdNumber.setProperty("intValue", 0)
        self.elapsedTimeLcdNumber.setObjectName(_fromUtf8("elapsedTimeLcdNumber"))
        self.horizontalLayout_7.addWidget(self.elapsedTimeLcdNumber)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_7 = QtGui.QLabel(self.widget3)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_4.addWidget(self.label_7)
        self.errorConnLcdNumber = QtGui.QLCDNumber(self.widget3)
        self.errorConnLcdNumber.setMinimumSize(QtCore.QSize(0, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.errorConnLcdNumber.setPalette(palette)
        self.errorConnLcdNumber.setDigitCount(5)
        self.errorConnLcdNumber.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.errorConnLcdNumber.setObjectName(_fromUtf8("errorConnLcdNumber"))
        self.verticalLayout_4.addWidget(self.errorConnLcdNumber)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.widget4 = QtGui.QWidget(monitoringDialog)
        self.widget4.setGeometry(QtCore.QRect(20, 260, 491, 32))
        self.widget4.setObjectName(_fromUtf8("widget4"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.widget4)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.monitoringOkPushButton = QtGui.QPushButton(self.widget4)
        self.monitoringOkPushButton.setObjectName(_fromUtf8("monitoringOkPushButton"))
        self.horizontalLayout_6.addWidget(self.monitoringOkPushButton)

        self.retranslateUi(monitoringDialog)
        QtCore.QObject.connect(self.monitoringOkPushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), monitoringDialog.close)
        QtCore.QMetaObject.connectSlotsByName(monitoringDialog)

    def retranslateUi(self, monitoringDialog):
        monitoringDialog.setWindowTitle(_translate("monitoringDialog", "Monitoring Connections", None))
        self.label.setText(_translate("monitoringDialog", "Script Used:", None))
        self.monitoringScriptLabel.setText(_translate("monitoringDialog", "N/A", None))
        self.label_2.setText(_translate("monitoringDialog", "Destination List Used:", None))
        self.monitoringListLabel.setText(_translate("monitoringDialog", "N/A", None))
        self.label_3.setText(_translate("monitoringDialog", "Number of Threads:", None))
        self.monitoringThreadsLabel.setText(_translate("monitoringDialog", "0", None))
        self.label_4.setText(_translate("monitoringDialog", "Total Number of Devices", None))
        self.label_5.setText(_translate("monitoringDialog", "Progress:", None))
        self.monitoringProgressLabel.setText(_translate("monitoringDialog", "0%", None))
        self.label_6.setText(_translate("monitoringDialog", "Successful Connections", None))
        self.label_8.setText(_translate("monitoringDialog", "Elapsed Time", None))
        self.label_7.setText(_translate("monitoringDialog", "Connection with Errors", None))
        self.monitoringOkPushButton.setText(_translate("monitoringDialog", "Ok", None))

