# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'monitoring.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_monitoringDialog(object):
    def setupUi(self, monitoringDialog):
        monitoringDialog.setObjectName("monitoringDialog")
        monitoringDialog.setWindowModality(QtCore.Qt.NonModal)
        monitoringDialog.resize(531, 295)
        monitoringDialog.setMinimumSize(QtCore.QSize(531, 295))
        monitoringDialog.setMaximumSize(QtCore.QSize(531, 295))
        monitoringDialog.setModal(True)
        self.line = QtWidgets.QFrame(monitoringDialog)
        self.line.setGeometry(QtCore.QRect(320, 20, 20, 81))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(monitoringDialog)
        self.line_2.setGeometry(QtCore.QRect(20, 110, 491, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(monitoringDialog)
        self.line_3.setGeometry(QtCore.QRect(20, 150, 491, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.widget = QtWidgets.QWidget(monitoringDialog)
        self.widget.setGeometry(QtCore.QRect(20, 20, 301, 81))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.monitoringScriptLabel = QtWidgets.QLabel(self.widget)
        self.monitoringScriptLabel.setObjectName("monitoringScriptLabel")
        self.horizontalLayout.addWidget(self.monitoringScriptLabel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.monitoringListLabel = QtWidgets.QLabel(self.widget)
        self.monitoringListLabel.setObjectName("monitoringListLabel")
        self.horizontalLayout_2.addWidget(self.monitoringListLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.monitoringThreadsLabel = QtWidgets.QLabel(self.widget)
        self.monitoringThreadsLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.monitoringThreadsLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.monitoringThreadsLabel.setLineWidth(0)
        self.monitoringThreadsLabel.setObjectName("monitoringThreadsLabel")
        self.horizontalLayout_3.addWidget(self.monitoringThreadsLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.widget1 = QtWidgets.QWidget(monitoringDialog)
        self.widget1.setGeometry(QtCore.QRect(350, 20, 158, 81))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.widget1)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.TotalLcdNumber = QtWidgets.QLCDNumber(self.widget1)
        self.TotalLcdNumber.setMinimumSize(QtCore.QSize(0, 50))
        self.TotalLcdNumber.setDigitCount(5)
        self.TotalLcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.TotalLcdNumber.setObjectName("TotalLcdNumber")
        self.verticalLayout_2.addWidget(self.TotalLcdNumber)
        self.widget2 = QtWidgets.QWidget(monitoringDialog)
        self.widget2.setGeometry(QtCore.QRect(20, 130, 491, 20))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.widget2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.monitoringProgressBar = QtWidgets.QProgressBar(self.widget2)
        self.monitoringProgressBar.setMaximum(100)
        self.monitoringProgressBar.setProperty("value", 0)
        self.monitoringProgressBar.setTextVisible(False)
        self.monitoringProgressBar.setObjectName("monitoringProgressBar")
        self.horizontalLayout_4.addWidget(self.monitoringProgressBar)
        self.monitoringProgressLabel = QtWidgets.QLabel(self.widget2)
        self.monitoringProgressLabel.setMinimumSize(QtCore.QSize(30, 0))
        self.monitoringProgressLabel.setObjectName("monitoringProgressLabel")
        self.horizontalLayout_4.addWidget(self.monitoringProgressLabel)
        self.widget3 = QtWidgets.QWidget(monitoringDialog)
        self.widget3.setGeometry(QtCore.QRect(20, 170, 491, 81))
        self.widget3.setObjectName("widget3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget3)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.widget3)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.SuccConnLcdNumber = QtWidgets.QLCDNumber(self.widget3)
        self.SuccConnLcdNumber.setMinimumSize(QtCore.QSize(0, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 178, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 178, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.SuccConnLcdNumber.setPalette(palette)
        self.SuccConnLcdNumber.setDigitCount(5)
        self.SuccConnLcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.SuccConnLcdNumber.setObjectName("SuccConnLcdNumber")
        self.verticalLayout_3.addWidget(self.SuccConnLcdNumber)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_8 = QtWidgets.QLabel(self.widget3)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_5.addWidget(self.label_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.elapsedTimeLcdNumber = QtWidgets.QLCDNumber(self.widget3)
        self.elapsedTimeLcdNumber.setMinimumSize(QtCore.QSize(0, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.elapsedTimeLcdNumber.setPalette(palette)
        self.elapsedTimeLcdNumber.setDigitCount(8)
        self.elapsedTimeLcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.elapsedTimeLcdNumber.setProperty("intValue", 0)
        self.elapsedTimeLcdNumber.setObjectName("elapsedTimeLcdNumber")
        self.horizontalLayout_7.addWidget(self.elapsedTimeLcdNumber)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.widget3)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_4.addWidget(self.label_7)
        self.errorConnLcdNumber = QtWidgets.QLCDNumber(self.widget3)
        self.errorConnLcdNumber.setMinimumSize(QtCore.QSize(0, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.errorConnLcdNumber.setPalette(palette)
        self.errorConnLcdNumber.setDigitCount(5)
        self.errorConnLcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.errorConnLcdNumber.setObjectName("errorConnLcdNumber")
        self.verticalLayout_4.addWidget(self.errorConnLcdNumber)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.widget4 = QtWidgets.QWidget(monitoringDialog)
        self.widget4.setGeometry(QtCore.QRect(20, 260, 491, 32))
        self.widget4.setObjectName("widget4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget4)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.monitoringOkPushButton = QtWidgets.QPushButton(self.widget4)
        self.monitoringOkPushButton.setObjectName("monitoringOkPushButton")
        self.horizontalLayout_6.addWidget(self.monitoringOkPushButton)

        self.retranslateUi(monitoringDialog)
        self.monitoringOkPushButton.clicked.connect(monitoringDialog.close)
        QtCore.QMetaObject.connectSlotsByName(monitoringDialog)

    def retranslateUi(self, monitoringDialog):
        _translate = QtCore.QCoreApplication.translate
        monitoringDialog.setWindowTitle(_translate("monitoringDialog", "Monitoring Connections"))
        self.label.setText(_translate("monitoringDialog", "Script Used:"))
        self.monitoringScriptLabel.setText(_translate("monitoringDialog", "N/A"))
        self.label_2.setText(_translate("monitoringDialog", "Destination List Used:"))
        self.monitoringListLabel.setText(_translate("monitoringDialog", "N/A"))
        self.label_3.setText(_translate("monitoringDialog", "Number of Threads:"))
        self.monitoringThreadsLabel.setText(_translate("monitoringDialog", "0"))
        self.label_4.setText(_translate("monitoringDialog", "Total Number of Devices"))
        self.label_5.setText(_translate("monitoringDialog", "Progress:"))
        self.monitoringProgressLabel.setText(_translate("monitoringDialog", "0%"))
        self.label_6.setText(_translate("monitoringDialog", "Successful Connections"))
        self.label_8.setText(_translate("monitoringDialog", "Elapsed Time"))
        self.label_7.setText(_translate("monitoringDialog", "Connection with Errors"))
        self.monitoringOkPushButton.setText(_translate("monitoringDialog", "Ok"))

